### ISSUE TITLE
pyzmq cannot be installed with "pip install --isolated"

### ISSUE THREAD

**Issue by mkoeppe** [zeromq/pyzmq#937]
`pip install --isolated` translates to `setup.py install --no-user-cfg`, which is not supported by pyzmq's `setup.py`

```
error: error in command line: command 'Configure' has no such option 'no_user_cfg'
Running setup.py install for pyzmq: finished with status 'error'
```

(See https://trac.sagemath.org/ticket/9536)

**Comment by minrk** [comment]
I just ran `pip install --isolated` with pip 9.0.1, setuptools 28.8.0, and it does work. What versions are you using?

**Comment by mkoeppe** [comment]
Thanks for looking into this.
In Sage we are using pip 8.1.2 and setuptools 24.0.2.
I'll try with upgrading these packages.

**Comment by minrk** [comment]
@mkoeppe it looks like it's not an issue with pip version or pyzmq, but the command sage is using to install pyzmq, [which is](https://git.sagemath.org/sage.git/tree/build/pkgs/pyzmq/spkg-install#n17):

    $PIP_INSTALL --global-option configure --global-option --zmq="$SAGE_LOCAL" .

`configure` is not a global option, it's a command. The result is that any arguments pip wants to pass to install are getting passed to configure instead. Since configure is run by default anyway, I think removing `--global-option configure` should fix the sage build.

**Comment by mkoeppe** [comment]
Thanks very much! Just removing `--global-option configure` didn't suffice; but a soluting in which I pass zmq configure option via `setup.cfg` does work. Thanks again, this issue can be closed.

**Comment by minrk** [comment]
Oh, I think the other should be changed to `--install-option` instead of `--global-option`, too.

**Comment by mkoeppe** [comment]
Well, if I try `pip install --ignore-installed --verbose --no-deps --no-index --isolated --install-option --zmq="$SAGE_LOCAL" .`, I still get 
```error: error in command line: command 'Configure' has no such option 'no_user_cfg'```

(But this is still using the old versions of pip and setuptools)

**Comment by minrk** [comment]
Okay, strange.
